Correcting CalendarColors names
The "CalendarColor" names seem to start with a small not a capital "L".
To keep a consistent namescheme "MaxColor" and "Auto" should be renamed to "maxColor" and "auto", too.
( In row 1499 it is already "auto")



I encountered this problem when my code throwed the following error while trying to get a calendar:

>>> schedule = account.schedule()
>>> calendar = schedule.get_calendar(calendar_name='Heizung')

ValueError: 'lightGreen' is not a valid CalendarColors

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    calendar = schedule.get_calendar(calendar_name='Heizung')
  File "E:\Programme\Python\Python3\lib\site-packages\O365\calendar.py", line 1849, in get_calendar
    **{self._cloud_data_key: data})
  File "E:\Programme\Python\Python3\lib\site-packages\O365\calendar.py", line 1501, in __init__
    self.color = CalendarColors(color)
  File "E:\Programme\Python\Python3\lib\enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "E:\Programme\Python\Python3\lib\enum.py", line 561, in __new__
    raise exc
  File "E:\Programme\Python\Python3\lib\enum.py", line 545, in __new__
    result = cls._missing_(value)
  File "E:\Programme\Python\Python3\lib\enum.py", line 574, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'lightGreen' is not a valid CalendarColors


I'm using a private outlook account (wich is accessed through "https://outlook.live.com/") by the way.
Buissnes / school accounts are accessed through "https://outlook.office365.com/owa/" (i can't log in there with my private account).
Maybe Microsoft has an inconsistent color name convention here (difference between private and buissnes).
This should be checked before merging my pull request.